import type { Skill, Bounty } from "./types";

export const SKILLS: Skill[] = [
  {
    id: "1",
    name: "Obstacle Avoidance v2.1",
    category: "NAVIGATION",
    description: "3D depth-aware collision prevention for autonomous mobile platforms.",
    longDescription:
      "Uses fused LiDAR + stereo vision data to build a real-time occupancy grid. Dynamically adjusts velocity and trajectory when obstacles are detected within configurable safety radii. Supports static and moving obstacles with predictive path re-planning.",
    price: 5,
    dev: "robodev_ko",
    rating: 4.8,
    reviews: 32,
    downloads: 1200,
    version: "2.1.4",
    compatibleDevices: ["Unitree Go2", "Spot", "Nav2 Stack"],
    tags: ["lidar", "stereo", "mobile"],
  },
  {
    id: "2",
    name: "Gesture Controller",
    category: "PERCEPTION",
    description: "Real-time hand gesture recognition mapped to robot control commands.",
    longDescription:
      "MediaPipe-based hand landmark detection running at 30fps. Supports 12 configurable gesture-to-command mappings including directional movement, speed control, arm articulation, and stop/emergency signals. Works indoors up to 4m range.",
    price: 12,
    dev: "mech_haus",
    rating: 4.6,
    reviews: 18,
    downloads: 450,
    version: "1.3.0",
    compatibleDevices: ["Any ROS2 node", "Unitree H1"],
    tags: ["vision", "mediapipe", "hri"],
  },
  {
    id: "3",
    name: "Patrol Route Manager",
    category: "SECURITY",
    description: "Configurable waypoint patrol with anomaly detection and event logging.",
    longDescription:
      "Define patrol routes as JSON waypoint arrays. The skill navigates the route autonomously, logs timestamps and sensor readings at each waypoint, and flags anomalies (unexpected obstacles, motion, thermal variance) to a configurable webhook endpoint.",
    price: 8,
    dev: "robo_nomad",
    rating: 4.9,
    reviews: 54,
    downloads: 2100,
    version: "3.0.1",
    compatibleDevices: ["Unitree Go2", "Boston Dynamics Spot", "Nav2"],
    tags: ["security", "patrol", "logging"],
  },
  {
    id: "4",
    name: "Object Pick & Place",
    category: "MANIPULATION",
    description: "6-DOF arm skill for grasping and placing objects by category.",
    longDescription:
      "Combines YOLOv8 object detection with inverse kinematics planning for a 6-DOF robotic arm. Supports tabletop grasping of 50+ object classes. Configurable grasp strategies (pinch, power, lateral). Integrates with ROS2 MoveIt2.",
    price: 20,
    dev: "arm_labs",
    rating: 4.7,
    reviews: 27,
    downloads: 890,
    version: "1.8.2",
    compatibleDevices: ["UR5", "Franka Panda", "xArm 6"],
    tags: ["manipulation", "yolo", "moveit2"],
  },
  {
    id: "5",
    name: "Voice Command Parser",
    category: "COMMUNICATION",
    description: "Natural language command parsing with intent routing for robot actions.",
    longDescription:
      "Whisper-based speech-to-text with a lightweight intent classifier. Routes commands to registered skill handlers. Supports custom vocabulary extension via YAML config. Latency under 400ms on edge hardware.",
    price: 7,
    dev: "syntax_bot",
    rating: 4.5,
    reviews: 15,
    downloads: 380,
    version: "1.1.0",
    compatibleDevices: ["Any Origin runtime host"],
    tags: ["nlp", "whisper", "voice"],
  },
  {
    id: "6",
    name: "SLAM Navigator",
    category: "NAVIGATION",
    description: "Simultaneous localisation and mapping with loop closure for unknown environments.",
    longDescription:
      "Based on Cartographer with custom loop closure tuning for indoor environments. Builds and maintains a 2D occupancy map while localising the robot in real time. Map is persisted between sessions and exportable as PGM.",
    price: 35,
    dev: "map_forge",
    rating: 5.0,
    reviews: 12,
    downloads: 290,
    version: "1.0.3",
    compatibleDevices: ["Unitree Go2", "Nav2 Stack"],
    tags: ["slam", "cartographer", "mapping"],
  },
  {
    id: "7",
    name: "Face Recognition Gate",
    category: "SECURITY",
    description: "Authorised-person verification with configurable access control actions.",
    longDescription:
      "FaceNet embeddings stored locally, no cloud dependency. Enrol faces via the Origin dashboard. When an unrecognised face is detected the robot triggers a configurable action: hold position, alert webhook, or return to base.",
    price: 18,
    dev: "vision_x",
    rating: 4.4,
    reviews: 9,
    downloads: 180,
    version: "2.0.0",
    compatibleDevices: ["Unitree H1", "Any camera-equipped robot"],
    tags: ["face", "security", "edge-ml"],
  },
  {
    id: "8",
    name: "Terrain Analyser",
    category: "PERCEPTION",
    description: "Classifies ground surface type and slope for adaptive gait selection.",
    longDescription:
      "Fuses IMU, pressure sensor, and camera data to classify terrain as: flat, gravel, grass, stairs, slope. Outputs confidence-weighted terrain type to the gait controller. Reduces falls by 60% on legged robots in field tests.",
    price: 15,
    dev: "ground_fx",
    rating: 4.7,
    reviews: 22,
    downloads: 640,
    version: "1.4.1",
    compatibleDevices: ["Unitree Go2", "Unitree B1", "Spot"],
    tags: ["terrain", "imu", "legged"],
  },
];

export const BOUNTIES: Bounty[] = [
  {
    id: "1",
    title: "Warehouse Inventory Scanner",
    description:
      "Build a skill that uses RGB-D data to scan shelf barcodes and update inventory in real time via REST API. Must handle motion blur and partial occlusion. Tested against a provided ROS2 bag file.",
    amount: 2500,
    manufacturer: "Unitree Inc.",
    status: "OPEN",
    daysLeft: 14,
    submissions: 3,
    requiredCategory: "PERCEPTION",
    postedAt: "2026-03-10",
  },
  {
    id: "2",
    title: "Outdoor Terrain Mapping",
    description:
      "Long-range terrain mapping skill for agricultural robots. Must cover 1 hectare autonomously, export a GeoTIFF, and handle GPS-denied zones using visual odometry fallback.",
    amount: 5000,
    manufacturer: "AgriBot Systems",
    status: "OPEN",
    daysLeft: 21,
    submissions: 7,
    requiredCategory: "NAVIGATION",
    postedAt: "2026-03-05",
  },
  {
    id: "3",
    title: "Multi-Robot Collision Avoidance",
    description:
      "Decentralised collision avoidance for a fleet of 10+ robots in a shared workspace. No central coordinator. Must maintain throughput above 80% of single-robot baseline.",
    amount: 3500,
    manufacturer: "FleetCore",
    status: "IN_REVIEW",
    daysLeft: 2,
    submissions: 12,
    requiredCategory: "NAVIGATION",
    postedAt: "2026-02-20",
  },
  {
    id: "4",
    title: "Voice-Controlled Arm Skill",
    description:
      "Natural language control for a 6-DOF arm. Commands like 'pick up the red bottle' should work end-to-end. Integration with Whisper + custom intent router required.",
    amount: 1800,
    manufacturer: "RoboArm Labs",
    status: "COMPLETED",
    daysLeft: null,
    submissions: 5,
    requiredCategory: "MANIPULATION",
    postedAt: "2026-02-01",
  },
];

export const PLATFORM_STATS = {
  totalSkills: 142,
  totalVolume: 48200,
  activeDevs: 89,
  openBounties: 11,
  totalBountyUsdc: 38500,
};
